const artists = [
  { slug: "miles-davis", artist: "Miles Davis", song: "Blue In Green", embed: "TLDflhhdPCg" },
  { slug: "brian-wilson", artist: "Brian Wilson", song: "Let's Go Away for Awhile", embed: "SEoKf52h9ok" },
  { slug: "john-lennon", artist: "John Lennon", song: "God", embed: "MDXxilRkw34" },
  { slug: "kate-bush", artist: "Kate Bush", song: "This Woman's Work", embed: "UXzx--YefD8" },
  { slug: "lou-reed", artist: "Lou Reed", song: "Perfect Day", embed: "9wxI4KK9ZYo" },
  { slug: "david-bowie", artist: "David Bowie", song: "Heroes (live)", embed: "LBpyJ3bqs6I" },
  { slug: "janis-joplin", artist: "Janis Joplin", song: "Ball & Chain (live)", embed: "X1zFnyEe3nE" },
  { slug: "elton-john", artist: "Elton John", song: "Curtains", embed: "g_bJhnJlCDg" },
  { slug: "kurt-cobain", artist: "Kurt Cobain", song: "All Apologies", embed: "0LFVQpDKHk4" },
  { slug: "tony-iommi", artist: "Tony Iommi", song: "Spiral Architect", embed: "lkx7SQ4Wuh0" },
  { slug: "jimmy-page", artist: "Jimmy Page", song: "That's the Way", embed: "GGsmyqIrZRo" },
  { slug: "billy-joel", artist: "Billy Joel", song: "Captain Jack", embed: "2xxugNQUtpE" },
  { slug: "sandy-denny", artist: "Sandy Denny", song: "I'll Keep It with Mine", embed: "CUtFXmS9FmA" },
  { slug: "jim-morrison", artist: "Jim Morrison", song: "The End", embed: "9pRGoSbYHQE" },
  { slug: "roy-orbison", artist: "Roy Orbison", song: "In Dreams", embed: "mSeIh9rmEUs" },
  { slug: "elvis-presley", artist: "Elvis Presley", song: "An American Trilogy (live)", embed: "0FT3SmZ_zx0" },
  { slug: "frank-sinatra", artist: "Frank Sinatra", song: "I've Got A Crush On You (Live At The Sands Hotel And Casino/1966)", embed: "5xcwSV0WvYg" },
  { slug: "ravi-shankar", artist: "Ravi Shankar", song: "Ravi Shankar at Monterey Pop (June 1967)", embed: "lk60ObnbIOk" },
  { slug: "grace-slick", artist: "Grace Slick", song: "Today (live)", embed: "XzPDZINn9V0" },
  { slug: "paul-mccartney", artist: "Paul McCartney", song: "Let Me Roll It", embed: "kWFehaQEMYI" },
  { slug: "freddy-mercury", artist: "Freddie Mercury", song: "Don't Stop Me Now", embed: "HgzGwKwLmgM" },
  { slug: "peter-allen", artist: "Peter Allen", song: "Quiet Please, There's a Lady on Stage", embed: "WoOfc3YJ3hM" },
  { slug: "pete-townshend", artist: "Pete Townshend", song: "Imagine a Man", embed: "sBN5U-nA6Is" },
  { slug: "carlos-santana", artist: "Carlos Santana", song: "Life Is A Lady/Holiday", embed: "GZ2ya7G7wlI" },
  { slug: "george-harrison", artist: "George Harrison", song: "Something", embed: "UelDrZ1aFeY" },
  { slug: "roger-daltry", artist: "Roger Daltrey", song: "See Me Feel Me", embed: "NzuNJod_o7g" },
  { slug: "nico", artist: "Nico", song: "Femme Fatale", embed: "ggHPtzVSEeE" },
  { slug: "john-lydon", artist: "John Lydon", song: "Pretty Vacant", embed: "R6GDdKrQ8EI" },
  { slug: "gary-numan", artist: "Gary Numan", song: "Cars", embed: "LrjM8Fi7J58" },
  { slug: "nina-simone", artist: "Nina Simone", song: "I Shall Be Released (live)", embed: "w-du8MDE8nk" },
  { slug: "scott-walker", artist: "Scott Walker", song: "Plastic Palace People", embed: "ayrS74ktTyE" },
  { slug: "neil-young", artist: "Neil Young", song: "Cortez The Killer", embed: "uX9k9aoX6gk" },
  { slug: "paul-simon", artist: "Paul Simon", song: "Graceland", embed: "H9M4XJXnCcw" },
  { slug: "stevie-wonder", artist: "Stevie Wonder", song: "Sir Duke", embed: "6sIjSNTS7Fs" },
  { slug: "marvin-gaye", artist: "Marvin Gaye", song: "What's Going On", embed: "H-kA3UtBj4M" },
  { slug: "aretha-franklin", artist: "Aretha Franklin", song: "Bridge Over Troubled Water", embed: "_9-yfeA2JZs" },
  { slug: "barbara-streisand", artist: "Barbra Streisand", song: "Send In The Clowns", embed: "FEbafV3PFuQ" },
  { slug: "barry-white", artist: "Barry White", song: "I've Got So Much to Give", embed: "RVF_H21yg9E" },
  { slug: "bob-marley", artist: "Bob Marley", song: "Could You Be Loved", embed: "sL_BcaI0i0w" },
  { slug: "devo", artist: "Gerald Casale", song: "Planet Earth", embed: "yzwrefrmNAM" },
  { slug: "ralf-hutter", artist: "Ralf Hutter", song: "Spiegelsaal", embed: "fzNOEpZSMwM" },
  { slug: "leo-sayer", artist: "Leo Sayer", song: "Giving It All Away", embed: "6OEarewzmwI" },
  { slug: "split-enz", artist: "Split Enz", song: "Message To My Girl", embed: "n0pcM30pjgQ" },
];
